name: leetcode
description: Solutions to leetcode problems in Dart.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  collection: ^1.17.1
  characters: ^1.2.1
  checks: ^0.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
